FROM node:22-alpine AS builder
WORKDIR /app
COPY backend/package*.json ./
RUN npm install --legacy-peer-deps
COPY backend ./
RUN npm run build

FROM node:22-alpine AS runner
WORKDIR /app
COPY backend/package*.json ./
RUN npm install --production --legacy-peer-deps
COPY --from=builder /app/dist ./dist
EXPOSE 4000
CMD ["node", "dist/index.js"]
